pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-project"
        DOCKER_USER = "yourdockerhubusername"
    }

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/yourusername/end-to-end-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_USER/$IMAGE_NAME:v1 app/'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $DOCKER_USER/$IMAGE_NAME:v1'
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh 'kubectl apply -f kubernetes/'
            }
        }
    }
}